#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use \Michael\Jobs\Utils;
define('MJOBS_ROOT_PATH', __DIR__);

require MJOBS_ROOT_PATH . '/vendor/autoload.php';
//初始化
date_default_timezone_set('Asia/Shanghai');
//加载配置
$config = require_once MJOBS_ROOT_PATH . '/config.php';
Utils::setConfig($config);
//Console实例
$appName = Utils::arrayGet($config,'system',"Michael jobs app");
$appVersion = Utils::arrayGet($config,'version',"V1.0");
//
$application = new Application($appName, $appVersion);
// 注册命令
$application->add(new \Michael\Jobs\Command\JobStartCommand);
$application->run();







