#!/usr/bin/env php
<?php

use \Michael\Jobs\Utils;

define('MJOBS_ROOT_PATH', __DIR__);

require MJOBS_ROOT_PATH . '/vendor/autoload.php';
//初始化
date_default_timezone_set('Asia/Shanghai');
//加载配置
$config = require_once MJOBS_ROOT_PATH . '/config.php';
//启动
Utils::run($config);







